mongodb/docs-tools

giza/giza/operations/stage.py
Please do not merge.
Issues
=====
* On a case-preserving filesystem like HFS (by default), this can lead to redirects being incorrectly removed.
=> stage: Fix redirects masking files

giza/giza/content/images/views.py
=> images: Don't generate a figure context in latex

sphinxext/tabs.py
DO NOT MERGE UNTIL LINKED TO A mongodb/docs PR
=> Remove requirement for all drivers in the set to be present in tabs.

sphinxext/tabs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-tools/170)
=> DOCSP-1649: Motor tab

data/bi-connector-published-branches.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-tools/177)
=> DOCS-11221 - Updating BIC published branches for 2.4

sphinxext/tabs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-tools/179)
=> tabs: Refactor extension

giza/requirements.txt, giza/setup.py
Added a [JSX Pygments lexer](https://github.com/fcurella/jsx-lexer) to support ReactJS code blocks.
```
.. code-block:: jsx
(props) => <div>{props.children}</div>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-tools/181)
=> Add JSX Pygments Lexer

tools/world-builder/projects.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-tools/192)
=> Add 3.6 for the manual

tools/screenshot-tool/screenshots.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-tools/198)
=> Adding logintoatlas function

data/bi-connector-published-branches.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-tools/200)
=> Adding BI Connector 2.5 upcoming branch

data/bi-connector-published-branches.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-tools/203)
=> DOCS-11684 - BI Connector v2.5 GA Release (stable)

sphinxext/tabs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-tools/206)
=> Adding a tab set for authentication protocols.

data/manual-published-branches.yaml, data/mms-published-branches.yaml
This reverts commit a71ddf31fd40457c26acac54ff26b17a3d995ae5.
=> Revert "Revert "4.0 release" " as ready for GA

data/bi-connector-published-branches.yaml
PLEASE LEAVE FOR JON TO MERGE.
=> Branch prep for BIC v2.6

tools/atlas-api-automation/.gitignore, tools/atlas-api-automation/README.md, tools/atlas-api-automation/differ.py, tools/atlas-api-automation/whitelist.txt
=> (DOCSP-3237) documented endpoints vs. programmatic discovery tool

data/manual-published-branches.yaml
merge when ready to create 4.2 branch in docs -- also in concert with undoing 
https://github.com/mongodb/docs/commit/63ae5727b147152d0a3668f2cc76a43593b4ab1e
=> 4.2 upcoming

data/charts-published-branches.yaml
Do not merge yet. Waiting until 12/20 morning when we publish.
=> Updating charts published branches for v0.11

data/ruby-driver-published-branches.yaml
=> Add ruby driver 2.7

themes/kubernetes-operator/footer.html, themes/kubernetes-operator/page.html, themes/kubernetes-operator/pagenav.html, themes/kubernetes-operator/search.html, themes/kubernetes-operator/theme.conf
@i80and : [Looks and works right](https://docs-mongodbcom-staging.corp.mongodb.com/kubernetes-operator/anthonysansone/master/index.html). Should be good to go.
=> (DOCSP-4794): Added theme for Kubernetes Operator.

data/kubernetes-operator-published-branches.yaml
Must be merged with https://github.com/10gen/docs-k8s-operator/pull/42
=> DOCSP-5509 - Update Kubernetes 0.11 to stable.

themes/mms-cloud/page.html, themes/mms-onprem/page.html
JIRA: https://jira.mongodb.org/browse/DOCSP-5760
Broken: https://docs.opsmanager.mongodb.com/v4.1/
Staged: https://docs-staging.cloudmanager.mongodb.com/jdestefano/DOCSP-5760/index.html
=> DOCSP-5760 - Update the margin to fix CM/OM banner button.

data/kubernetes-operator-published-branches.yaml
Must be merged with:
https://github.com/10gen/docs-k8s-operator/pull/47
=> DOCSP-5805 - Version bump for k8s 0.12

data/kubernetes-operator-published-branches.yaml
We are bumping to 1.1 for a new release and need to prep a 1.2 so we have an easier transition to that version when it comes.
=> Updated for Operator v1.1

data/manual-published-branches.yaml
@i80and  -- whenever you get a chance this afternoon.
=> DOCS-12158: 4.2 manual ga

data/realm-published-branches.yaml, themes/realm/page.html, themes/realm/pagenav.html, themes/realm/realm-adblock-header.html, themes/realm/realm-adblock.html, themes/realm/search.html, themes/realm/theme.conf
This adds the necessary theming for Realm.
=> add realm theme

data/node-driver-published-branches.yaml, data/php-library-published-branches.yaml
This adds placeholder branch information so we can work on node driver migration
=> Add node driver

data/kubernetes-operator-published-branches.yaml, sphinxext/tabs.py
=> DOCSP-7412 - Update k8s published branches

sphinxext/stitch_release_notes.py
https://jira.mongodb.org/browse/DOCSP-5391
=> (DOCSP-5391): Fix Release Notes Directive Date Parsing

data/kubernetes-operator-published-branches.yaml
Update published branches for the v1.4 release.
=> (DOCSP-8032): Update K8s Op published branches

sphinxext/icon.py
[JIRA](https://jira.mongodb.org/browse/DOCSP-8619)
=> (DOCSP-8619): adding undo fa4 icon

data/php-library-published-branches.yaml
JIRA: https://jira.mongodb.org/browse/DOCSP-8994
=> DOCSP-8994: update php driver docs version to 1.6

themes/mongocli/footer.html, themes/mongocli/page.html, themes/mongocli/pagenav.html, themes/mongocli/search.html, themes/mongocli/theme.conf
[JIRA](https://jira.mongodb.org/browse/DOCSP-9120)
- Created a theme for the new mongocli docs. 
- Added an Alpha warning banner.
=> (DOCSP-9120): Create mongocli theme

sphinxext/tabs.py
Based on the definitions in this JIRA ticket: https://jira.mongodb.org/browse/DOCSPLAT-274
Needed for Stitch->Realm migration sphinx builds.
=> Add Realm tabbing directives

data/kafka-connector-published-branches.yaml
-fix the branch info (forgot the "v")
=> fix version selector for kafka connector docs

data/kafka-connector-published-branches.yaml
Another attempt to get the version selector right.
=> Kafka Connect: add master to published versions

data/mongocli-published-branches.yaml
Updating to v0.5.0(current) and v1.0.0(upcoming)
=> (DOCSP-10392): Mongocli version update

data/php-library-published-branches.yaml
JIRA:
https://jira.mongodb.org/browse/DOCSP-10188
Staging:
No visible content to view on stage.
=> DOCSP-10188: update php published branches to include v1.7

data/mongocli-published-branches.yaml
Updating to v1.0.0(current) and v1.1.0(upcoming).
=> (DOCSP-10688): Mongocli version update to v1.0

data/mongocli-published-branches.yaml
[JIRA](https://jira.mongodb.org/browse/DOCSP-11427)
=> (DOCSP-11446): Mongocli version bump to v1.3

data/php-library-published-branches.yaml
Update PHP docs stable version to v1.7
=> DOCSP-11542: update php docs stable version

data/kubernetes-operator-published-branches.yaml
=> (DOCSP-11803): version bump kubernetes operator

themes/mongodb/src/css/basic.css
[JIRA](https://jira.mongodb.org/browse/DOP-1130). [Snooty PR](https://github.com/mongodb/snooty/pull/247). This PR removes the flashing yellow highlighting effect due to previsualization in next-gen. 
- [Datalake - h1](https://docs-mongodbcom-staging.corp.mongodb.com/master/datalake/cgoecknerwald/DOP-1130/reference/api/dataLakes-get-all-tenants#get-all-data-lakes)
- [Datalake - h2](https://docs-mongodbcom-staging.corp.mongodb.com/master/datalake/cgoecknerwald/DOP-1130/reference/api/dataLakes-get-all-tenants#base-url)
- [Datalake - h3](https://docs-mongodbcom-staging.corp.mongodb.com/master/datalake/cgoecknerwald/DOP-1130/reference/api/dataLakes-get-all-tenants#request-path-parameters)
- [Datalake - code](https://docs-mongodbcom-staging.corp.mongodb.com/master/datalake/cgoecknerwald/DOP-113 …
=> DOP-1130-2: Remove highlighting from dt:target

data/mongoid-published-branches.yaml
JIRA:
https://jira.mongodb.org/browse/DOCSP-12050
=> DOCSP-12050: Add Mongoid 5.4 to version selector

data/kafka-connector-published-branches.yaml
JIRA:
https://jira.mongodb.org/browse/DOCSP-12535
=> DOCSP-12535: add v1.3 to Kafka Connector docs

data/kubernetes-operator-published-branches.yaml
@schmalliso when you have a minute, can you please sanity check this PR to bump the kubernetes operator version? Thank you!
=> (DOCSP-12578): version bumping k8s operator

data/manual-published-branches.yaml
Update to match new Server Manual versioning in prep for upcoming releases. Please reach out to me with any questions. Thank you!
=> update manual to use new v4.4 branch, reserve master for upcoming

data/mongoid-published-branches.yaml, data/ruby-driver-published-branches.yaml
Added new versions of Ruby and Mongoid docs per request: https://jira.mongodb.org/browse/DOCSP-13417
=> DOCSP-13417: add new versions of ruby and mongoid

sphinxext/icon.py
- [JIRA](https://jira.mongodb.org/browse/DOCSP-13519)
=> DOCSP-13519 adding ellipsis-v to the fa4 iconset

data/php-library-published-branches.yaml
https://jira.mongodb.org/browse/DOCSP-13908
=> DOCSP-13908: update php library version version

sphinxext/icon.py
- [JIRA](https://jira.mongodb.org/browse/DOCSP-15264)
=> DOCSP-15264 adding hand-pointer-o to the fa4 iconset

sphinxext/icon.py
- [JIRA](https://jira.mongodb.org/browse/DOCSP-15272)
=> DOCSP-15272 adding fa-files-o icon to the fa4 iconset

sphinxext/icon.py
- [JIRA](https://jira.mongodb.org/browse/DOCSP-15300)
=> DOCSP-15300 adding mouse-pointer icon to FA4 iconset

sphinxext/icon.py
- [JIRA](https://jira.mongodb.org/browse/DOCSP-15913)
=> DOCSP-15913 Add share-square-o icon to the FA4 iconset

data/mongoid-published-branches.yaml
https://jira.mongodb.org/browse/DOCSP-16025
=> Added Mongoid 7.3

data/kubernetes-operator-published-branches.yaml
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60f07e63a1eeec1fdc053807)
[Jira](https://jira.mongodb.org/browse/DOCSP-17437)
Related PR in MEKO is https://github.com/10gen/docs-k8s-operator/pull/655
=> (DOCSP-17347) MEKO version bump to v1.12

themes/mms-cloud/page.html, themes/mms-cloud/theme.conf
[JIRA Ticket](https://jira.mongodb.org/browse/DOCSP-18494)
[Staging Link ](https://docs-cloudmanager-staging.mongodb.com/mongodb-docs/DOCSP-18494/index.html)
=> (DOCSP-18494) Create a banner for automation eol

data/php-library-published-branches.yaml
=> add php 1.10

themes/mms-cloud/theme.conf, themes/mms-onprem/theme.conf
- [JIRA](https://jira.mongodb.org/browse/DOCSP-21728)
=> DOCSP-21728 update to theme.conf file

themes/mms-onprem/page.html, themes/mms-onprem/theme.conf
Reverts mongodb/docs-tools#582
=> Revert "(DOCSP-23690) Warn users that OM 4.4 and 5.0 will soon be EOL"

themes/mms-onprem/page.html, themes/mms-onprem/theme.conf
This PR re-applies changes from a previous PR with fixes suggested by @gjchong25
=> (DOCSP-23690) Adds 4.4 and 5.0 EOL approaching banners

data/mms-published-branches.yaml
Reverts mongodb/docs-tools#590
this didn't address the root issue.
=> Revert "DOCSP-24211: OM current -> 6.0"

data/kubernetes-operator-published-branches.yaml
[Jira](https://jira.mongodb.org/browse/DOCSP-25446)
=> (DOCSP-25446): update version kubernetes 1.17

themes/mms-cloud/page.html, themes/mms-cloud/theme.conf, themes/mms-onprem/page.html
Adds a new banner for OM and CM to indicate that support is now ended, plus makes a few other changes while I'm in here
=> (DOCSP-24806) Changes OM EOL message for backup/monitoring support

data/php-library-published-branches.yaml
[PR Reviewing Guidelines](https://github.com/mongodb/docs-ecosystem/blob/master/REVIEWING.md)
JIRA - <https://jira.mongodb.org/browse/DOCSP-26681>
=> DOCSP-26681 PHP 1.15 Version Updates

themes/mongodb/layout.html
My understanding is that we want everything to have a canonical URL that points to /current/ or whatever and also for robots to be set to index. So that's what I've done.
=> DOP-3376: everything should have a canonical

data/kubernetes-operator-published-branches.yaml
[Jira](https://jira.mongodb.org/browse/DOCSP-27202)
=> (DOCSP-27202) updates versions for v1.18 release.

data/kubernetes-operator-published-branches.yaml
[Jira](https://jira.mongodb.org/browse/DOCSP-27209)
Build
Staging
=> (DOCSP-27209) Removes deprecated MEKO versions.

data/php-library-published-branches.yaml
https://jira.mongodb.org/browse/DOCSP-30907
=> DOCSP-30907: add PHP library 1.16

data/kubernetes-operator-published-branches.yaml
[JIRA](https://jira.mongodb.org/browse/DOCSP-30904)
=> (DOCSP-30904): removes EOL MEKO versions.

data/ruby-driver-published-branches.yaml
[JIRA ticket](https://jira.mongodb.org/browse/DOCSP-31133)
=> DOCSP-31133: add Ruby 1.x

data/mongoid-published-branches.yaml
[JIRA ticket](https://jira.mongodb.org/browse/DOCSP-31096)
=> DOCSP-31096: mongoid 8.1 updates

data/mongoid-published-branches.yaml
JIRA: https://jira.mongodb.org/browse/DOCSP-30857
=> DOCSP-30857: update published versions for Mongoid

themes/mongodb/layout.html
updated trailing slash for [DOP-3970](https://jira.mongodb.org/browse/DOP-3970).
=> updated trailing slash

data/kubernetes-operator-published-branches.yaml
[Jira](https://jira.mongodb.org/browse/DOCSP-30905)
=> (DOCSP-30905):  Remove EOL meko version 1.18

data/mms-published-branches.yaml
This reverts commit 26a39fe62d2b2df843303a36bf0022cfb1756eac.
=> Revert "(DOCSP-34603) Updates OM upcoming to v7.0 branch (#644)"

data/mms-published-branches.yaml
This reverts commit 3b5ada4596ba0d47acd61923bd2cc477168c5461.
=> Revert "(DOCSP-34603) Adds v7.0 branch to published branches (#646)"

data/mms-published-branches.yaml
[Jira](https://jira.mongodb.org/browse/DOCSP-35245)
=> (DOCSP-35245): Update version flipper for OM 7.0 release
