- giza/giza/cmdline.py
- giza/giza/config/main.py
- giza/giza/config/paths.py
- giza/giza/operations/stage.py
``Configuration.deploy`` and ``Configuration.test`` were relative, causing them to be invalid whenever they were accessed while underneath the project root.
``giza stage`` only needed to fix the former, but I took the liberty of applying the same fix to the latter.
> Make stage and test work in project subdirectories

- giza/giza/config/runtime.py
Change default screen logging level to "warn", and only log "warn" to the giza.log file regardless of what "-l" option is set.
> Fix broken logging levels

- giza/giza/content/options/models.py
- giza/giza/content/options/tasks.py
This doesn't actually work, and I'm not sure why. When I build, it doesn't seem to even be *aware* that there's a `filename` field, and yet there definitely is?
[Here's the commit I've got in the docs repo for it…](https://github.com/schmalliso/docs-mongodb/commit/2965f32003851aadd3a433e772ebcea8a326471b)
> DOCS-9100: adds support for options that differ only by case

- themes/mongodb/src/css/mongodb-docs.css
Related PR on `mongodb/docs-landing`: [https://github.com/mongodb/docs-landing/pull/10](https://github.com/mongodb/docs-landing/pull/10)
> DOCSP-998: Prevent sidebar overlapping main content.

- themes/mongodb/layout.html
The G+ link has been broken for a while. MongoDB.com does not use it, but it does use Stack Overflow. I swapped in SO for G+.
> Removed G+ icon and link. Replaced with Stack Overflow per MongoDB.com.

- sphinxext/tabs.py
Adds tabs for both methods of developing Stitch applications (**Import/Export** and **Stitch UI**)
```restructuredtext
.. tabs-stitch-interfaces::
hidden: true
tabs:
- id: stitch-ui
content: |
Some Stitch UI content
- id: import-export
content: |
Some Import/Export content
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-tools/201)
> Add stitch interface tabs

- sphinxext/tab-content.py
This directive lets you specify content that should only appear for one tab of a pre-defined tab set
> Add tab-content directive

- sphinxext/sphinx_openapi.py
[Jira Ticket](https://jira.mongodb.org/browse/DOCSP-3267)
This fix adds conditional `list-table` rendering when a response doesn't explicitly define response fields (e.g. [this 204 response](https://github.com/10gen/baas-docs/blob/master/source/openapi-admin-v3.yaml#L264)).
> (DOCSP-3267): Fix OpenAPI Build Warning

- sphinxext/mongodb_conf.py
The only thing I'm not sure about is what `prepend` and `callable` do, but trying this locally worked.
> Add config-expansion directive for server

- sphinxext/mongodb_conf.py
- sphinxext/stitch-builders.py
We're now distinguishing between **Expansions** and **Operators** in JSON expressions (Stitch rules). These directives let us tag the directives in an appropriate manner.
**Note:** This PR changes the ``.. expansion::`` directive, which is only used in the Stitch docs.
> Add JSON expression directives

- themes/charts/page.html
@tomhollander: This changes the heading for Charts to include the word "Beta". If it is unclear, I will copy into the ticket and ref you there.
> (DOCSP-4083): Updated Charts language to include beta.

- data/bi-connector-published-branches.yaml
JIRA: https://jira.mongodb.org/browse/DOCSP-4898
Related release notes PR: https://github.com/mongodb/docs-bi-connector/pull/216
> DOCSP-4898 - Update BIC published branches for v2.10.0

- data/charts-published-branches.yaml
- themes/charts/page.html
**Please do not merge until Thursday, June 13th afternoon**
We need to:
1. Remove `beta` from the top-level banner.
2. Unpublish all beta docs prior to and equal to 0.12.
3. Create a new release docset called "19.06". Per the Charts status meeting, we will label this `19.06 (On-Prem)` in the UI. The corresponding github branch is `19-06`.
> Updates for Charts GA

- sphinxext/mongodb_conf.py
This is required to support DOCSP-5037 in cloud-docs.
> DOCSP-5037: Data Lake Configuration Reference

- data/manual-published-branches.yaml
Upon cursory look, I think this is what appends the (current) 
My cursory search has:
https://github.com/mongodb/docs-tools/blob/ebf42b4f03ee323d6916692a685f546240dc54c1/giza/giza/config/git.py#L94-L101
and then
https://github.com/mongodb/docs-tools/blob/ebf42b4f03ee323d6916692a685f546240dc54c1/giza/giza/config/project.py#L21-L44
> DOCS-12158: 4.2 manual ga (part2)

- data/mms-published-branches.yaml
This prepares the `mms-docs` repo for v4.3 and v4.4. It will need to be released for MongoDB 4.2 today (13 Aug 2019).
> (DOCSP-6535): Updated branches for OM 4.3, 4.4

- sphinxext/mongodb_conf.py
Need to prepend the tag to bsontypes to distinguish between other directives (e.g. method Date/ObjectId/UUID vs bsontype Date/ObjectId/UUID)
> DOCSP-7119: prepend for bsontype directive

- sphinxext/mongodb_conf.py
[JIRA](https://jira.mongodb.org/browse/DOCSP-7436)
adding new directive to work around issue with reusing :settings: with the same name on multiple pages
> (DOCSP-7436): adding k8s-op-om-setting directive

- sphinxext/tabs.py
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/kubernetes-operator/jdestefano/DOCSP-7374/tutorial/deploy-standalone.html
Builds clean without error symlinked on my local:
```
~/git/docs-k8s-operator(DOCSP-7374) $ make clean-html
rm -rf build/DOCSP-7374
giza make html
INFO:giza.operations.make:running sphinx build operation, equivalent to: giza sphinx --builder html
INFO:giza.content.assets:updated /Users/jdestefano/git/docs-k8s-operator/build/docs-tools repository
INFO:giza.content.source:created directory for sphinx build: /Users/jdestefano/git/docs-k8s-operator/build/DOCSP-7374/source
INFO:giza.content.source:prepared and migrated source for sphinx build in /Users/jdestefano/git/docs-k8s-operator/build/DOCSP-7374/source
INFO:giza.operations.sphinx:adding builder job for html …
```
> DOCSP-7374 - Add tabs for k8s orchestrator.

- data/kafka-connector-published-branches.yaml
Updates kafka branches for 0.2 only without displaying current next to it because it looks like 💩
> update kafka branches

- themes/manual/pagenav.html
- themes/mongodb/layout.html
[[JIRA](https://jira.mongodb.org/browse/DOCSP-8255)] [[Meta Staging](https://docs-mongodbcom-staging.corp.mongodb.com/meta/sophstad/master/index.html)]
- Add more robust error handling for generating version dropdown labels
- Since `docs-meta` is not a versioned repo, hide the version dropdown from the site. This implementation is a little hacky, but I imagine meta will be moved on to next-gen before too long.
> DOCSP-8255: Fix meta builds

- data/kafka-connector-published-branches.yaml
Update the Kafka Connector version selector to show 1.0 only.
JIRA: https://jira.mongodb.org/browse/DOCS-13344
> update version of Kafka connector to 1.0

- sphinxext/tabs.py
@i80and : This change helps users understand that Debian and Ubuntu are the same thing (generally) and adds a new tab type for server platforms.
(This simplifies the request in [DOCSP-8688](https://jira.mongodb.org/browse/DOCSP-8688) asking to pull out Ubuntu from Debian, even though every download for our products equates the two. Discussed with James Broadhead and Andrey Belik from Private Cloud.)
> (DOCSP-8688): Update Platform Terms

- sphinxext/tabs.py
@i80and : I checked it all out. 
Built successfully:
```
➜  mms-docs git:(DOCSP-8815) make clean-html-opsmgr
rm -rf build/DOCSP-8815
giza make html-onprem
INFO:giza.operations.make:running sphinx build operation, equivalent to: giza sphinx --builder html --edition onprem
INFO:giza.content.assets:updated /home/atsansone/projects/mms-docs/source/figures repository
INFO:giza.content.assets:updated /home/atsansone/projects/mms-docs/build/docs-tools repository
INFO:giza.content.source:created directory for sphinx build: /home/atsansone/projects/mms-docs/build/DOCSP-8815/source-onprem
INFO:giza.content.source:redacted 27 files
INFO:giza.content.source:prepared and migrated source for sphinx build in /home/atsansone/projects/mms-docs/build/DOCSP-8815/source-onprem …
```
> (DOCSP-8688): Updated Platform Tab Labels

- themes/mongocli/page.html
I realized too late that I implemented an alert type that you can dismiss. I do want the alert to persist on each page.
> (DOCSP-9120-patch): Update mongocli theme's alpha alert type

- data/mongocli-publishsed-branches.yaml
Created a published branches yaml file for the new 10gen/mongocli repo.
There will be a current v0.0.3 and an upcoming v0.0.4. The current is based off the v0.0.3 branch, and the upcoming is based on master.
> (DOCSP-9364): Create mongocli-published-branches.yaml

- data/kafka-connector-published-branches.yaml
Add v1.1 to Kafka Connector for new release
JIRA: https://jira.mongodb.org/browse/DOCSP-10089
> update version selector for Kafka Connector 1.1

- themes/database-tools/footer.html
- themes/database-tools/page.html
- themes/database-tools/pagenav.html
- themes/database-tools/search.html
- themes/database-tools/theme.conf
Theme required for docs.mongodb.com/database-tools
We're currently using the local fork for this. Once this is merged to master, we can switch back to docs-tools core.
cc @jdestefano-mongo
> DOCSP-9010: Add new theme for docs.mongodb.com/database-tools

- data/kubernetes-operator-published-branches.yaml
- themes/kubernetes-operator/page.html
- themes/kubernetes-operator/theme.conf
[JIRA](https://jira.mongodb.org/browse/DOCSP-10269)
@jdestefano-mongo Could you take a look and make sure I don't need to do anything else? I used the [PR to remove OM 2.0](https://github.com/mongodb/docs-tools/commit/28acc210a6285d128b789bce67f543623ebc96ab) and the PR to [unpublish OM pre-2.0](https://github.com/mongodb/docs-tools/commit/713f8f8df3a1b105459dcaa4086b761a7af89a81) as references.
It looks like [the page knows](https://github.com/mongodb/docs-tools/blob/master/themes/mongocli/page.html#L24) to put a deprecation notice at the top of the docs if the version isn't listed in the active branches. Do I need to add `active_branches =` to the [theme](https://github.com/mongodb/docs-tools/blob/master/themes/mongocli/theme.conf) make this work? The [OM …
> (DOCSP-10269): Remove pre-1.0 versions of k8s docs

- data/kafka-connector-published-branches.yaml
JIRA: 
https://jira.mongodb.org/browse/DOCSP-11113
No staging (version selector update)
> DOCSP-11113: Update Kafka Connector versions file to include 1.2

- data/manual-published-branches.yaml
Prepwork for the upcoming 4.4 manual publish.  This PR must be merged before the Server Team can publish the 4.4 docs.
> prepwork for 4.4 manual publish

- themes/charts/page.html
We no longer want to have a banner on the saas side directing users to the onprem docs. We just want a banner directing users from onprem -> saas.
staged: 
(non-master branch): https://docs-mongodbcom-staging.corp.mongodb.com/charts/jeffreyallen/DOCSP-11490/index.html
(master / saas branch): https://docs-mongodbcom-staging.corp.mongodb.com/charts/jeffreyallen/master/index.html
> (DOCSP-11490): Update Charts theme to remove redirect to onprem

- data/mms-published-branches.yaml
@jdestefano-mongo : I followed [these instructions](https://docs.mongodb.com/meta/tutorials/version-bumping/) on Docs Meta. Matches changes done in https://github.com/10gen/mms-docs/pull/3212.
> (DOCSP-11448) Update versions for Ops Manager 4.4.0

- data/bi-connector-published-branches.yaml
JIRA: https://jira.mongodb.org/browse/DOCS-13789
> DOCS-13789 - Remove v2.9 and earlier from the BIC version selector.

- themes/mongodb/src/widgets/deluge/MainWidget.js
**NextGen/Snooty Widget:** https://github.com/mongodb/snooty/pull/318
https://jira.mongodb.org/browse/DOP-1631
> (DOP-1631): Update feedback widget to point to Community instead of Google Groups

- data/mms-published-branches.yaml
Updated published branches file for the v4.9.0 rapid release.
[JIRA](https://jira.mongodb.org/browse/DOCSP-13360)
> (DOCSP-13360): OM v4.9.0 Rapid Release

- data/mongocli-published-branches.yaml
Apparently, I didn't update this file for v1.8 a month ago... oops. This PR bumps the docs to v1.9 (stable) and includes the versions I missed for 1.8.
> (DOCSP-13395): Version bump to v1.9

- data/mms-published-branches.yaml
@i80and : This should retire version 4.0 of the Ops Manager docs per @gssbzn. Please let me know if all looks in order.
> (DOCSP-15037) Retire v4.0

- themes/mongodb/layout.html
Moves canonicalref block into an if statement so that it only is rendered if the version is in `theme_active_branches`, thus ensuring that we don't have canonical URLs on pages who have `robots: noindex,nofollow`, per advice of SEO consultants.
> DOP-2187: only include canonical block if version is active

- themes/mongoid/page.html
- themes/php-library/page.html
- themes/ruby-driver/page.html
- Uses correct URL string for canonical URLs for php-library and ruby-driver, per [DOP-2186](https://jira.mongodb.org/browse/DOP-2186) (for some reason, it was building with docs-php-library and docs-ruby as the theme_project strings. This seems like the easiest fix)
- Adds an HTML title block to the mongoid docs so that page titles will have "mongoid" in them, consistent with the ruby docs' format.
> DOP-2186, DOP-2112: canonical and title fixes

- data/kubernetes-operator-published-branches.yaml
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60b97baff1f693745039d6b3) - build fails but I have no idea if this is by design.
[Jira](https://jira.mongodb.org/browse/DOCSP-16402)
Created a new version for MEKO, 1.12.
Please review. Please note that in the 10gen/docs-k8s-operator, I only created a 1.11 branch. I didn't create 1.12. Here is the [commit](https://github.com/10gen/docs-k8s-operator/commit/390978c473cecf3a7024221246f7429712d88c91) for the release notes in that repo.
> (DOCSP-16402) Version bump for Kubernetes Operator v1.12

- data/mms-published-branches.yaml
- themes/mms-onprem/page.html
This PR corresponds with https://github.com/10gen/mms-docs/pull/3750 . It adds an EOL banner to the 4.2 docs similar to the one implemented in https://github.com/mongodb/docs-tools/pull/481.
> (DOCSP-16023): EOL 4.2 Banner

- data/mms-published-branches.yaml
Removes v4.2 from the version flipper for MMS/Ops Manager as that version is EOL.
> (DOCSP-17864) Removes v4.2 from version flipper for MMS

- giza/docs/source/.static/osd.xml
- themes/guides/layout.html
- themes/mongodb/layout.html
Switches favicon references to https://docs.mongodb.com/assets/favicon.ico
> DOP-2555: Switch media.mongodb.org favicon to docs s3 bucket

- themes/mms-onprem/page.html
- themes/mongodb/layout.html
Proposed naive fix for legacy version selector.
Potentially fixes observed behavior at https://www.mongodb.com/docs/kubernetes-operator/stable/
> Attach 'docs' to version pathing

- themes/mms-cloud/page.html
- themes/mms-onprem/page.html
- [JIRA](https://jira.mongodb.org/browse/DOCSP-21728)
> DOCSP-21728 Update Blue Banner EOL Alert for CM/OM pages

- giza/requirements.txt
Reverts mongodb/docs-tools#493
> Revert "Bump pygments from 2.4.2 to 2.7.4 in /giza"

- themes/mms-onprem/page.html
- themes/mms-onprem/theme.conf
OM 4.4 will be EOL later this month. 5.0 will be EOL in July 2023, but engineering has asked that we have a banner for it now/soon.
This PR adds an "EOL soon" banner for both 4.4 and 5.0. Only the 4.4 banner will be activated now (via a separate PR on the mms-docs repo). The 5.0 banner will be activated once 6.0 is GA, at which time we will also activate the existing  "theme_eol_remove" banner for 4.4 if the last release has gone out.
Text was approved by the PM (Evin Roesle) via Slack.
> (DOCSP-23690) Warn users that OM 4.4 and 5.0 will soon be EOL

- data/mongoid-published-branches.yaml
- data/php-library-published-branches.yaml
- data/ruby-driver-published-branches.yaml
This adds new versions to the drop-down selector for ruby, PHP, and mongoid.
> add new versions of php, ruby, and mongoid

- data/kubernetes-operator-published-branches.yaml
[DOCSP-22196](https://jira.mongodb.org/browse/DOCSP-22196)
Changes:
Removed MEKO 1.11, 1.12, and 1.13 based on the [EOL dates](https://www.mongodb.com/docs/kubernetes-operator/master/reference/support-lifecycle/#k8s-support-lifecycle).
Used these [instructions](https://wiki.corp.mongodb.com/display/DE/How+To%3A+Sunset+a+Version+of+Documentation/) for sunsetting docs that use legacy builds.
> Sunset MEKO 1.11, 1.12, 1.13

- data/manual-published-branches.yaml
We're publishing a new version of the docs, v6.1. v6.1 content lives on the `master` branch, and v6.0 content lives on the `v6.0` branch.
> (DOCSP-25053): Update legacy version flipper for 6.1 upcoming

- themes/mongodb/layout.html
This PR uses the existing canonical link block only for, but for all, EOL'd properties.
* Manual v4.0: `<link rel="canonical" href="https://www.mongodb.com/docs/manual/" />`
* Ops Manger v4.0: `<link rel="canonical" href="https://www.mongodb.com/docs/ops-manager/current/" />`
* Ops Manger master: no `<link>` tag
* K8s Connector master: no `<link>` tag
* K8s Connector v1.1: `<link rel="canonical" href="https://www.mongodb.com/docs/kubernetes-operator/master/" />`
> DOP-3241: Include canonical links for EOL properties, remove noindex,nofollow meta tags

- data/kubernetes-operator-published-branches.yaml
[DOCSP](https://jira.mongodb.org/browse/DOCSP-28878) and related tickets.
> (DOCSP-28788) Adding MEKO 1.19.x, removing MEKO 1.16 from published branches due to EOL

- themes/kubernetes-operator/page.html
The canonical references for the kubernetes pages were changed from `master` to `current`. We've never used `current` for this docs set, but we use `stable`.  We've received reports from the SEO team that google is trying to crawl /current/*, so we should probably fix this.
Updating this in the theme.
> change current to stable in kubernetes page theme

- themes/mms-cloud/page.html
- themes/mms-cloud/theme.conf
- themes/mms-onprem/page.html
- themes/mms-onprem/theme.conf
[Jira](https://jira.mongodb.org/browse/DOCSP-28448)
Will be staged with mms-docs, but this part has to be merged into docs-tools first
Using [this wiki](https://wiki.corp.mongodb.com/pages/viewpage.action?pageId=149195138)
Rephrased the copy from the ticket
> CM docs message - 
"On June 16h, 2023, we will be ending SNMP and Manage Sharded Collections UI support for MongoDB in Cloud Manager. We will remove these features from the UI completely, at a later date. The removal of Manage Sharded Collections UI does not cause any impact to your sharded clusters."
OM docs message -
"In Ops Manager 7.0, we will be removing SNMP and Manage Sharded Collections UI support for MongoDB in Ops Manager. The removal of Manage Sharded Collections UI does not cause any impact to your sharded clusters."
> (DOCSP-28448) [OM/CM] Managed Sharded Collection EOL banner

- data/mms-published-branches.yaml
Updates docs-tools based on legacy instructions from [the wiki](https://wiki.corp.mongodb.com/display/DE/How+To%3A+Sunset+an+EOL+Version+of+Documentation#HowTo:SunsetanEOLVersionofDocumentation-LegacyInstructions).
[Jira](https://jira.mongodb.org/browse/DOCSP-31800)
> (DOCSP-31800): Move OM 5.0 docs to the legacy site

- data/mms-published-branches.yaml
We want the v7.0 branch of mms-docs to display when a user selects "Upcoming" in the docs. "master" branch content will soon be limited to CM content only in preparation for the OM/CM migration to Snooty.
> (DOCSP-34603) Updates OM upcoming to v7.0 branch
